default_rank_op: Apprentice, Red
default_rank_no_op: Camper, White
rank_limit: 3
ranks:
  - Admin, Red, true
  - Tech, Blue, false
  - Magic, Light_Purple, false
  - Cool, Gold, false, true
  - Green, Red, false
peaceful_radius: 20
peaceful_interval: 100